"""Initial

Revision ID: a473563b8d6b
Revises: 
Create Date: 2022-11-25 06:36:15.743338

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a473563b8d6b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.Unicode(length=255), nullable=False),
        sa.Column("password", sa.Unicode(length=255), nullable=False),
        sa.Column("deposit", sa.Float(), nullable=False),
        sa.Column("role", sa.Enum("buyer", "seller", name="roles"), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("product_name", sa.Unicode(length=255), nullable=False),
        sa.Column("seller_id", sa.BigInteger(), nullable=False),
        sa.Column("amount_available", sa.Integer(), nullable=False),
        sa.Column("cost", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    op.drop_table("users")
    # ### end Alembic commands ###
